version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  jobs:
    pre_build:
      - pip install sphinx-intl
      - pwd && ls -al
      - cd docs && sphinx-build -b gettext . ../_build/gettext
      - sphinx-intl update -p _build/gettext -l ko

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false
  builder: html

python:
  install:
    - requirements: requirements.txt

# Build documentation in all languages
formats:
  - htmlzip
  - pdf
