version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true
  builder: html
  jobs: 2
  verbose: 1

python:
  install:
    - requirements: requirements.txt

# Build documentation in all languages
formats:
  - htmlzip
  - pdf
